In [17]:
import pandas as pd

from pathlib import Path

DATA_DIR = "/home/sequenzia/dev/solen-rl-project/data"

all_infer_data = {}

OUTPUT_DIR = f"{DATA_DIR}/reports"

for file_path in  Path(DATA_DIR).glob("*.parquet"):
    
    run_key = file_path.stem
    run_data = pd.read_parquet(file_path)

    run_data['run_key'] = run_key

    run_data = run_data[['run_key', 'scores', 'times', 'lengths']]

    run_data.to_markdown(f"{OUTPUT_DIR}/{run_key}.md", index=False)

    all_infer_data[run_key] = run_data

In [15]:
all_infer_data['A2C_BREAKOUT']

# for key, data, in all_infer_data.items():
#

          run_key  scores       times  lengths
0    A2C_BREAKOUT   423.0    8.698921  12125.0
1    A2C_BREAKOUT   485.0   17.828901  13619.0
2    A2C_BREAKOUT   428.0   27.674914  14202.0
3    A2C_BREAKOUT   785.0   47.787560  30254.0
4    A2C_BREAKOUT   440.0   77.776392  44116.0
..            ...     ...         ...      ...
115  A2C_BREAKOUT   418.0  230.889643   9507.0
116  A2C_BREAKOUT   859.0  243.935879  19721.0
117  A2C_BREAKOUT   477.0  253.334306  14438.0
118  A2C_BREAKOUT   441.0  265.694379  18927.0
119  A2C_BREAKOUT   376.0  270.955272   8013.0

[120 rows x 4 columns]