In [6]:
import wandb
api = wandb.Api()
run = api.run("/appliedtheta/Solen-RL-Project/4r30pbj8")

run_data = run.history()

run_data

,_runtime,time/total_timesteps,_step,rollout/ep_rew_mean,global_step,_timestamp,time/fps,rollout/ep_len_mean,time/time_elapsed,rollout/exploration_rate,train/loss,time/episodes,eval/mean_ep_length,train/learning_rate,train/n_updates,eval/mean_reward
0,10.720071,3508.0,0,-20.500000,3508.0,1.702903e+09,1125.0,3526.000000,3.0,0.998264,NaN,4.0,NaN,NaN,NaN,NaN
1,13.705776,7152.0,1,-20.375000,7152.0,1.702903e+09,1171.0,3595.125000,6.0,0.996460,NaN,8.0,NaN,NaN,NaN,NaN
2,20.149830,10000.0,2,NaN,10000.0,1.702903e+09,NaN,NaN,NaN,0.995050,NaN,NaN,4009.199951,NaN,NaN,-20.200001
3,24.194498,14821.0,4,-20.312500,14821.0,1.702903e+09,893.0,3726.250000,16.0,0.992664,NaN,16.0,NaN,NaN,NaN,NaN
4,27.339332,18610.0,5,-20.299999,18610.0,1.702903e+09,942.0,3743.649902,19.0,0.990788,NaN,20.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,15015.196033,2694042.0,701,19.840000,2694042.0,1.702918e+09,179.0,6887.890137,15007.0,0.010000,0.000487,1732.0,NaN,0.0001,2594041.0,NaN
496,15060.203360,2700000.0,702,NaN,2700000.0,1.702918e+09,NaN,NaN,NaN,0.010000,0.000057,NaN,6788.200195,0.0001,2599999.0,20.200001
497,15067.847875,2701401.0,703,19.809999,2701401.0,1.702918e+09,179.0,6907.430176,15060.0,0.010000,0.000937,1736.0,NaN,0.0001,2601400.0,NaN
498,15106.514687,2708354.0,704,19.780001,2708354.0,1.702918e+09,179.0,6918.589844,15098.0,0.010000,0.000068,1740.0,NaN,0.0001,2608353.0,NaN
499,15128.342529,2710000.0,705,NaN,2710000.0,1.702918e+09,NaN,NaN,NaN,0.010000,0.000157,NaN,6605.000000,0.0001,2609999.0,20.400000